### ISSUE TITLE
Question? Witchery SRC

### ISSUE THREAD

**Issue by Mrdrewlego** [zabi94/Covens#1]
I do know having the witchery src is breaking its original license. I have an exact 1 to 1 copy of the witchery src for 1.7.10 and was wondering if you could help update it for newer platforms (1.8 or higher)? I have hardware limits making it hard to update anything past forge 1.7.10.

**Comment by zabi94** [comment]
1) It might be extremely difficult to update, so many things have changed since 1.7.10... 
2) As long as you keep it for yourself, you can decompile and use the original code without breaking the license 
3) I barely have the time to code covens, helping you would be impossible for me 
4) My hardware is old too, I cannot test server components freely either
5) I doubt you srcs are 1:1 unless you got them directly from emoniph, decompiling does not deobfuscate method names and breaks all annotations not marked for runtime retention (that includes all `@Override` notations). If you have somehow found original srcs I might consider it, but if you just decompiled it's really easier to start from 0
